package discoveryv3

// deterministicQuestions returns the hardcoded set of questions per level.
// Each question is deterministic — not generated by AI.
func deterministicQuestions(intentID string) []Question {
	var all []Question
	pos := 1

	for _, q := range projectQuestions(intentID) {
		q.Position = pos
		pos++
		all = append(all, q)
	}
	for _, q := range masterPlanQuestions(intentID) {
		q.Position = pos
		pos++
		all = append(all, q)
	}
	for _, q := range specificPlanQuestions(intentID) {
		q.Position = pos
		pos++
		all = append(all, q)
	}
	for _, q := range phaseQuestions(intentID) {
		q.Position = pos
		pos++
		all = append(all, q)
	}
	for _, q := range taskQuestions(intentID) {
		q.Position = pos
		pos++
		all = append(all, q)
	}

	return all
}

func projectQuestions(intentID string) []Question {
	return withIntent(intentID, LevelProject, []Question{
		{
			Question:      "What is the main goal or problem you are solving?",
			Reason:        "Defines the core purpose of the product and feeds Description.",
			Required:      true,
			RelatedFields: []string{"description"},
		},
		{
			Question:      "Who is the target user or audience?",
			Reason:        "Identifies the user and feeds DesiredExperience.",
			Required:      true,
			RelatedFields: []string{"desired_experience"},
		},
		{
			Question:      "What is the expected business outcome?",
			Reason:        "Captures the measurable result and feeds ExpectedOutcome.",
			Required:      false,
			RelatedFields: []string{"expected_outcome"},
		},
		{
			Question:      "What are the key constraints (budget, timeline, team)?",
			Reason:        "Documents restrictions that affect scope and approach.",
			Required:      false,
			RelatedFields: []string{"restrictions"},
		},
	})
}

func masterPlanQuestions(intentID string) []Question {
	return withIntent(intentID, LevelMasterPlan, []Question{
		{
			Question: "What are the major milestones or phases?",
			Reason:   "Defines the high-level structure of the master plan.",
			Required: true,
		},
		{
			Question: "What is the overall architecture approach?",
			Reason:   "Captures the technical direction and key design decisions.",
			Required: true,
		},
		{
			Question: "What are the key risks?",
			Reason:   "Identifies potential blockers early for risk mitigation.",
			Required: false,
		},
		{
			Question: "What is the timeline expectation?",
			Reason:   "Sets delivery cadence and milestone targets.",
			Required: false,
		},
		{
			Question: "What dependencies exist?",
			Reason:   "Identifies external dependencies or prerequisite work.",
			Required: false,
		},
	})
}

func specificPlanQuestions(intentID string) []Question {
	return withIntent(intentID, LevelSpecificPlan, []Question{
		{
			Question: "What specific feature or domain is this plan focused on?",
			Reason:   "Narrows scope from the master plan to a concrete deliverable.",
			Required: true,
		},
		{
			Question: "What are the detailed requirements?",
			Reason:   "Documents functional and non-functional requirements.",
			Required: true,
		},
		{
			Question: "What technologies will be used?",
			Reason:   "Captures tech stack decisions for this specific plan.",
			Required: false,
		},
		{
			Question: "What are the acceptance criteria?",
			Reason:   "Defines how we verify completion and quality.",
			Required: true,
		},
	})
}

func phaseQuestions(intentID string) []Question {
	return withIntent(intentID, LevelPhase, []Question{
		{
			Question: "What tasks does this phase include?",
			Reason:   "Breaks the phase into actionable work items.",
			Required: true,
		},
		{
			Question: "What is the expected duration?",
			Reason:   "Estimates time commitment for planning and scheduling.",
			Required: false,
		},
		{
			Question: "What dependencies must be completed first?",
			Reason:   "Identifies prerequisites to unblock this phase.",
			Required: false,
		},
	})
}

func taskQuestions(intentID string) []Question {
	return withIntent(intentID, LevelTask, []Question{
		{
			Question: "What is the task description?",
			Reason:   "Defines the work to be done at the granular task level.",
			Required: true,
		},
		{
			Question: "What files or areas will be affected?",
			Reason:   "Identifies the scope of changes for implementation.",
			Required: false,
		},
		{
			Question: "What testing strategy should be used?",
			Reason:   "Ensures quality through defined test approach.",
			Required: false,
		},
	})
}

func withIntent(intentID string, level DiscoveryLevel, qs []Question) []Question {
	for i := range qs {
		qs[i].IntentID = intentID
		qs[i].Level = level
	}
	return qs
}
