ALTER TABLE raw_inputs ADD COLUMN raw_content TEXT NOT NULL DEFAULT '';
ALTER TABLE ingested_sources ADD COLUMN normalized_content TEXT NOT NULL DEFAULT '';
ALTER TABLE ingested_sources ADD COLUMN classification TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE visions ADD COLUMN target_users TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN functional_goals TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN ux_goals TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN business_goals TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN constraints TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN assumptions TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN missing_information TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN visual_references TEXT NOT NULL DEFAULT '[]';
ALTER TABLE visions ADD COLUMN success_criteria TEXT NOT NULL DEFAULT '[]';
CREATE TABLE IF NOT EXISTS approved_requirements (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'approved', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, content));
CREATE TABLE IF NOT EXISTS approved_constraints (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'approved', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, content));
CREATE TABLE IF NOT EXISTS approved_decisions (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'approved', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, content));
CREATE TABLE IF NOT EXISTS approved_preferences (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'approved', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, content));
CREATE TABLE IF NOT EXISTS approved_references (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'approved', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, content));
CREATE TABLE IF NOT EXISTS approved_goals (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_id TEXT NOT NULL DEFAULT '', content TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'approved', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, content));
CREATE INDEX IF NOT EXISTS idx_ingested_sources_project ON ingested_sources(project_id);
CREATE INDEX IF NOT EXISTS idx_ingested_sources_classification ON ingested_sources(classification);
CREATE INDEX IF NOT EXISTS idx_approved_requirements_project ON approved_requirements(project_id);
CREATE INDEX IF NOT EXISTS idx_approved_constraints_project ON approved_constraints(project_id);
CREATE INDEX IF NOT EXISTS idx_approved_decisions_project ON approved_decisions(project_id);
CREATE INDEX IF NOT EXISTS idx_approved_preferences_project ON approved_preferences(project_id);
CREATE INDEX IF NOT EXISTS idx_approved_references_project ON approved_references(project_id);
CREATE INDEX IF NOT EXISTS idx_approved_goals_project ON approved_goals(project_id);
